# Dockerfile.mysql

FROM mysql:8.0

# Set environment variables
ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_DATABASE=ecom

# Optional: Copy init SQL scripts (if you have any)
# COPY init.sql /docker-entrypoint-initdb.d/
